server:
  port: 8090
  contextPath: /
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG
  
morganna:
  application:
    host: xxxxx
    loginLocation: /oauth2/alipay
    indexLocation: /index.html
    authErrorLocation: /form.html?error
    whitelists: /oauth2/alipay,/index.html,/form.html                              #白名单
  antplatform:
    appAuthorize: https://openauth.alipaydev.com/oauth2/publicAppAuthorize.htm     #支付宝用户登陆授权回调地址
    appAuth: https://openauth.alipaydev.com/oauth2/appToAppAuth.htm                #支付宝第三方应用授权回调地址
    url: https://openapi.alipaydev.com/gateway.do
    appId: 20160248
    privateKey: ADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeEpTXqI9qhGjmDQW/OeCbCkRJ1yWiAk0lzZQfS5zBXc7/9MhsNwAByhOfWkLvgvTBe8ONZe7mKGJDeLfVB+gUaNCd+1lcK4u8iHGigMM0FIJUt4lrBjxJT1od1/uLNTwUVYrc/H49BwMQPTHviqMxVn1vzmgT0GB0HRLxOuBorRMGWtSz70kBENEd0wwjAUwfyGe3WGnWdVG/Qpk9Zzc/A8GxNmSECnQL1MfgiLtOsiXFNeHvu8CCjq39kWGEgNIBzaCKAQaErdA5/AX3FDGT3REh4lX0fWxumtdgjx5tORKKpsmX16e5dysw4obZldaUjhwFQ7Lz7AbLKQfSwSf7AgMBAAECggEAHc4oo/k/pnA3FAlTaCMAfk6Wc8KojmH4sMYyxzCCzYElszzLWZrYKWVR1OVsbnEJIJ7X1DaGJeXtqlidc74n6/VVap69k51Ul+1IMyNND8Rg6bXof7DKjpxT4AWJAVoXwjLo/Ff3KYGza46LETduR8Tv+P2fAmnJSExOqonYbLPuBJYq3Ei6Rc5dww3aR5zxVuCxtf97TqT3XUHTWRwi6+2245qYmaQKA26kWC4ictFkW2zs4C/oK2/ub3+HpYfvBqNokKB7CuNQUov604C50GE5tT6uop6/UXI+agOFAGcQy4bbNmCabYKMbE3DPz/vDF8+9FJGeRJZQqIHKdTeQQKBgQDv5QydBHmfaY/LMOsBGCjRvAcY/GrIil2fQdqDnwG3RJbK8+NwBT/XLl+2kBNNJ7OhXm6JCUb4KgTzFB6PReh/oIl+FUXzsFG15bhRNyvMbaI08GZOCz5TsUM457ModiIMEXWPDJVvBZ9sE9Zw+/sA0kT6UCyaRgIcI0III2pOuQKBgQDs+ztfxxqqrqb8zbfOz/Yi90/mk0/Y/7chIyYs0Q188xKos7wSwbZdyF3oQOc1i9DKHHe1pt62FmkUOFJdrkAtokWr05Ru0SXgLuLOucAxbZ8ItX1QojEvyNJxS4RT6mYJioxrZyzHBLlOOQo8XrwQMO5Yqyi13FcMJ7+ZAnWyUwKBgBOQqbuwnr66nEilH7WCI+ofHLET/R2H82TGuSyc7kXlKSs6QuVi+DbziEjabUiQoVza18cDY69ftfGhRXDH8dNe43fOAluCmNdt+d9d0YulsWIB7UYWMqoeve3JL9pv8Azt65mUHCfm3H6zC31Bf9IsVAXaPhkC9q8WzQ7e3I+5AoGBAMGofNjEKHKazzOAGVkUcRwZ5l2SvImkTs7xnly5acBWE0Vxu5vIWXNCLhuCDm+fljvUD6+OcilzHuO7MvQDVcb0+OJ1wLLej4koR4iQGxNJddD0HzgpkvBtuCuFftnkjwX1BtMuOVVZ8uSNkGPNNvo0QlKLbHVRXoE8akJr1CqpAoGAIE8hofY1OPJlVjMRdXQ6ZszdDohWvdJYcQgeL/s+0HySlF/o8409w10Kp5ckAIAt8rSU/OW00+mVjXsDCEUqrnuzrzSqZZeX9TDh+6wQRob/uic3emUIXztEDhPXWWJawMtJAl7Sf379l9afMMFsazgMm1xzl+gyKXFICvatx
    alipayPublicKey: jANBgkqhkiFAAOCAQ8AMIIBCgKCAQEAvDelzFL9Pq1KxO0DHfnxcDOKUmlsS9eVZgqQjBPE+ZCW9a+fiplGwVnWnonAgSZ/0Y6SHuru3yA/IFjHrcNkD2iUGgv+ZppSXYFd/WHFX096h5BMoweN/P6kIBtOj1Pmz1Ig4xA0r729texeZRMaOAmcRHRdFmuYqebv6Cm8q0ztgxIO15/7hiMNbFiUAeDGhmAPm76MGubM6gTX7w26XvaEEvEwcuu8vR5Oh3uziM0xceKPmo/vSCpG0zWHZkbvzgnteFY2wjD2nEumoz0cQ9KoPji1Fs40YiW/QDFYeZV4552eVIANUXRLEE+sstgAj2NF+OkIWIFLW4fHBXfdVQIDA
    format: json
    charset: UTF-8
    scope: auth_user
    signType: RSA2                                                                 # sha256WithRsa 算法请求类型
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.cassandra.CassandraAutoConfiguration,
             org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration,
             org.springframework.boot.autoconfigure.data.cassandra.CassandraReactiveDataAutoConfiguration,
             org.springframework.boot.autoconfigure.data.cassandra.CassandraRepositoriesAutoConfiguration,
             org.springframework.boot.autoconfigure.data.cassandra.CassandraReactiveRepositoriesAutoConfiguration
    
