server:
  port: 8090
  contextPath: /
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG
  
spring:
  application: 
    name: morganna
    
